name: truesight_core
description: Core functions for TrueSight packages
version: 2312.17.1
# repository: https://github.com/my_org/my_repo

homepage: https://github.com/thanhtunguet

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  dio: ^4.0.0
  equatable: ^2.0.5
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
